packages:
  - packages/*
catalog:
  '@modelcontextprotocol/sdk': ^1.17.4
  '@types/next': ^9.0.0
  debug: ^4.4.1
  mcp-handler: ^1.0.2
  next: ^15.5.2
  zod: ^4.1.5
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    bumpp: ^10.1.0
    eslint: ^9.25.1
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.3
    unbuild: ^3.5.0
  testing:
    vitest: ^3.1.2
    vitest-package-exports: ^0.1.1
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
